= Stephans KMP Components
:doctype: book
:description: Documentation for Stephans KMP Components
:keywords: kotlin multiplatform, components
:icons: font
:toc:
:toc-title: Contents
:toclevels: 10

== Status

image:https://github.com/sknull/Stephans-KMP-Components/actions/workflows/publish.yml/badge.svg[Stephans-KMP-Components CI,link=https://github.com/sknull/Stephans-KMP-Components/actions/workflows/publish.yml]

== About

Some components I created for my KMP projects.
Also includes a fork of colorful sliders ported to kmp.
Sorry there is no documentation at all yet.

== License

link:LICENSE[GNU GENERAL PUBLIC LICENSE v3 (2007)]

This project is licensed under GPLv3. If you use this code in your app, your entire app must also be open-sourced under GPLv3.

=== What this means for you

You are free to use, modify, and distribute this software.Copyleft: If you use this code in your own project or app, your entire project must also be licensed under GPLv3 and its source code must be made public.This effectively prevents using this code in "closed-source" commercial apps. If you intend to sell an app based on this code without releasing your source code, you are in violation of this license.
